on:
  push:
name: release
jobs:
  GoReleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: "release --skip-publish --snapshot"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

